// Copyright © ByteHeed.  All rights reserved.

use ffi::traits::EncodeUtf16;


// #define IOCTL_SENTRY_CREATE_PARTITION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A00, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_DELETE_PARTITION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A01, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_GETOPTION_PARTITION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A02, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_SETOPTION_PARTITION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A03, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_REGISTER_GUARD \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A10, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_UNREGISTER_GUARD \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A11, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_CONTROL_GUARD \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A12, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_CREATE_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A20, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_DELETE_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A21, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_ADD_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A22, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_REMOVE_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A23, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_SET_STATE_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A24, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_GET_INFO_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A25, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define IOCTL_SENTRY_ENUMERATE_REGION \
//     CTL_CODE( IOCTL_SENTRY_TYPE, 0x0A26, METHOD_BUFFERED , FILE_READ_ACCESS | FILE_WRITE_ACCESS  )

// #define SE_NT_DEVICE_NAME     L"\\Device\\Sentry"
// #define SE_WIN32_DEVICE_NAME  L"\\DosDevices\\Sentry"